import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Globalprovider } from "@/GlobalProvider";
import Nav from "@/components/Nav/Nav";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Globalprovider>
          <Toaster
            position='bottom-right'
            toastOptions={{
              className: "toastFont",
              duration: 3000,
              style: {
                border: "2px solid #295f4e",
                borderRadius: "50px",
                textAlign: "center",
                whiteSpace: "nowrap",
                width: "fit-content",
              },
            }}
          />
          <Nav />
          {children}
        </Globalprovider>
      </body>
    </html>
  );
}
